afterEach(function () {
    //jest.unmock('crypto');
});

Object.defineProperty(window, 'jwtStrNormal', { value: 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInRva2VuLXR5cGUiOiJhY2Nlc3MtdG9rZW4iLCJuYmYiOjE1MjUzNjE5NjQsImlzcyI6Ii9vYXV0aDIvdG9rZW4iLCJncm91cHMiOlsiYWRtaW4iXSwidGFnLWludGVybmFsIjp7ImdyYW50LXR5cGUiOiJwYXNzd29yZCIsInByb2ZpbGUiOiJtb3ZpZXMiLCJ2ZXJzaW9uIjoiMS4wIiwidXNlcm5hbWUiOiJhZG1pbiJ9LCJleHAiOjE1MjUzNjM3NjQsImlhdCI6MTUyNTM2MTk2NCwianRpIjoiOTZjYjM3OTFmODY1ZTIzMSIsInVzZXJuYW1lIjoiYWRtaW4ifQ.m7dddcexisZeAoUQJPN1htGP753gV-uJrFkhThWmWZM' });
Object.defineProperty(window, 'jwtStrGzip', { value: 'eyJhbGciOiJIUzI1NiIsInppcCI6IkdaSVAifQ.eJxtjk0OgjAQhe8yaxALAsJVjIsCA1ahbToFNcS7OxAxMXE53_uZNwONFZQgm0FpCMCbG-rQPy0usK6RKFwZa7pqoRRpnCaZKLJDAIqIXZGRo7_E0WbrnBktC6dP6ZlbZRcq7dFp2UM5s0Vqv32xkuhuXMNR60yr-gUOZlJIjCZ0pIxmJHZ7vkdaWgb8bn4FgA-7DUvydZj0v0uvXnGgyOoqyQvRHrMU40T8rXsDw0VUkw.zLDFd5VLMe-Op1Ny7ENbdcGug0OlYdnGJWQLxvPaPFY' });
Object.defineProperty(window, 'jwtSecret', { value: 'test' });

